In [3]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr[-5:-1]

array([10, 20, 30, 40])

In [4]:
data = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
]
arr = np.array(data)
arr[ : 2, : 2]

array([[1, 2],
       [4, 5]])

In [5]:
scores = np.array([85,92,78,90,88])

In [6]:
en_yuksek = np.max(scores)
en_yuksek

92

In [7]:
en_dusuk = np.min(scores)
en_dusuk

78

In [8]:
ort = np.mean(scores)
ort

86.6

In [9]:
monthly_sales = np.array([1200,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400,2500])
ilk_alti_ay = monthly_sales[0:6]
ilk_alti_ay

array([1200, 1500, 1600, 1700, 1800, 1900])

In [10]:
ilk_alti_ay_ort = np.mean(ilk_alti_ay)
ilk_alti_ay_ort

1616.6666666666667

In [11]:
son_alti_ay = monthly_sales[6:]
son_ort = np.mean(son_alti_ay)
son_ort

2250.0

In [12]:
daily_production = np.random.randint(100,200,size = 30)
daily_production

array([199, 156, 155, 119, 192, 152, 198, 132, 176, 175, 109, 189, 147,
       189, 116, 152, 147, 129, 128, 163, 182, 131, 147, 125, 147, 128,
       124, 178, 136, 132])

In [13]:
top = np.sum(daily_production)
top

4553

In [14]:
ort_gun_uretim = np.mean(daily_production)
ort_gun_uretim

151.76666666666668

In [15]:
exam_scores = np.array([
    [85,90,88,92],
    [78,85,90,87],
    [92,88,82,95],
    [80,85,78,88]
])

In [16]:
ortalama = np.mean(exam_scores,axis = 1)
print('Ortalama: ',ortalama)

Ortalama:  [88.75 85.   89.25 82.75]


In [17]:
uzaklik = exam_scores - ortalama[:np.newaxis]
print(uzaklik)

[[ -3.75   5.    -1.25   9.25]
 [-10.75   0.     0.75   4.25]
 [  3.25   3.    -7.25  12.25]
 [ -8.75   0.   -11.25   5.25]]


In [18]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
             ])