In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr1 =np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
arr2 =np.zeros(100)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr3 = np.ones(100)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr4 = np.eye(50)
arr4

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
arr5 = np.linspace(0,100,3)
arr5

array([  0.,  50., 100.])

In [31]:
arr6 = np.random.randint(0,100)
arr6

90

In [39]:
arr7 = np.random.randint(0,100,1000)
arr7

array([52,  0, 88, 65, 53, 50, 73, 80, 99, 89, 56, 61, 82, 98, 53, 95, 12,
       87, 64, 78, 97, 45, 67, 38, 33, 23,  7, 19, 96, 79, 69,  2, 35, 53,
        9, 15, 77, 36, 70, 55, 74, 36, 10, 38, 71, 57, 40, 82, 65, 92, 42,
       99,  4, 49, 12, 51, 10,  7, 23, 66, 12, 21, 44, 65, 27, 80,  2, 31,
       26, 10, 22, 67, 54, 98, 45,  0, 59,  2, 42, 59, 94, 52, 58, 46, 65,
       19, 47, 99, 47, 75, 48, 59, 96,  9, 91,  7, 31, 34, 51, 99, 37, 25,
       42, 52, 76, 81, 44,  6, 12, 13,  3, 57, 69, 48, 46, 30, 32, 35, 25,
       22, 95, 78,  0, 91, 71, 67, 69, 17, 75, 85, 22, 10, 57, 94, 92, 95,
       69, 62, 68, 19, 64, 98, 43, 65, 32, 44, 37, 79, 18, 58, 35, 39, 28,
       70, 16, 44, 45, 89, 39, 28,  0, 72,  8, 24, 19, 71, 31,  7, 40, 85,
       27, 66, 74, 77, 52, 34,  9, 17, 83, 13, 14, 12, 86, 99, 75, 97, 12,
       98,  8, 77, 86, 62, 57,  3, 78, 37, 98, 82, 73, 81, 27, 13,  3, 32,
       99, 12, 49,  1, 50, 65, 87, 57, 42, 29, 55, 12, 76,  9, 29, 96, 86,
       79, 58, 44, 94, 83

In [43]:
arr8 = np.random.rand(10)
arr8

array([0.53842993, 0.83841766, 0.40861347, 0.52704049, 0.9524199 ,
       0.98235167, 0.38656395, 0.8888887 , 0.17502166, 0.5739897 ])

In [45]:
arr9 = np.random.randn(5)
arr9

array([-0.97296815,  1.81401882,  0.63252369,  0.77539154, -1.3514969 ])

In [65]:
arr0 = np.arange(1,170)
arr0

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169])

In [67]:
arr0.reshape(13,13)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52],
       [ 53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78],
       [ 79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156],
       [157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169]])

In [75]:
arr01 = arr0.min()
arr01

1

In [77]:
arr02 = arr0.max()
arr02

169

In [81]:
arr03 = arr0.argmin()
arr03

0

In [83]:
standart_sapma = np.std(arr0)
standart_sapma

48.78524367060187

In [85]:
ornek = np.eye(23)
ornek

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [93]:
ornek1 = np.arange(0,10,2)
ornek1

array([0, 2, 4, 6, 8])

In [115]:
ornek2 = np.random.randint(0,100,1000)
ornek3 = ornek2.reshape(10,100)
ornek3

array([[13, 49, 88, 30, 13, 12,  4, 13,  3,  6, 69, 77, 33, 56, 54, 26,
        74, 64, 11,  0,  3,  8, 67, 44, 41, 18, 26, 96, 12, 97, 62, 82,
        97, 25, 78, 63, 75, 66, 62, 69, 88, 99, 42,  1, 56, 14, 75, 66,
        84, 59, 76, 74,  5, 69, 90, 89,  3, 78, 91,  2, 93, 11, 49, 74,
        44, 27, 75, 63, 52, 97, 94, 85,  2, 47, 10, 55, 25, 40, 72, 97,
        78, 67, 51, 74, 28, 93,  1, 21, 55, 86, 53, 13, 35, 50, 84, 86,
         6,  6, 92, 61],
       [83,  1,  7, 13, 75, 31, 50, 38, 31, 43, 29,  8, 69, 48, 42,  4,
        54, 54,  1, 92, 81, 41, 29, 19, 96, 93, 67, 42, 36, 44, 91,  0,
        77, 81, 44, 53, 31, 71, 40,  1, 38, 32, 59, 24, 33, 11, 54, 57,
        37, 66, 44, 67, 95,  8,  4, 97, 72,  3, 37, 47, 71, 87, 63, 54,
         4, 32, 65, 35, 91, 74, 94, 57, 11, 51, 25, 38, 50,  6, 39, 58,
        99, 87, 86, 35, 79, 12, 93, 43, 28, 43, 73, 46, 53, 92, 17, 87,
         2,  1, 97, 14],
       [98, 96, 36, 93, 82, 64, 27, 88, 68, 10, 25, 49, 57, 82, 44, 88,
        66,  2

In [117]:
ornek4 = np.random.randint(0,100,1000)
ornek5 = np.random.randint(0,100,1000)

sum = ornek4 + ornek5
sum

array([ 96,  69,  75,  43, 118, 139, 102,  87, 131,  47, 146,  99,  69,
        57,  96,  51, 129,  90, 120,  67,  39, 100, 125, 142, 108, 145,
        86,  75,  73, 176,  71, 117, 128, 114, 137,  69,  89, 104,  42,
        57,  93,  48,  99, 153, 158, 106, 101,  76, 115, 171,  53,  68,
       168,  78, 131, 129, 114,  42, 100,  79, 128, 175,  50,  51,  94,
        77,  35,  82,  10, 168,  53, 126,  20, 131, 126,  62, 104, 127,
        88,  81,  60, 145,  38,  46, 109, 114,  53, 110,  65,  64,  10,
        43,  67,  69, 135,  85,  69,  89,  55,  74,  59,  36,  84,  84,
       143, 185,  79, 163,  22,  69, 111, 125, 110,  91,  91,  85,  95,
       117,  90,  59, 160, 142,  31,  72, 128,  43,  74,  95, 105, 126,
        97,  70,  55,  21,  93, 117,  63, 117,  89, 103, 136, 124,  93,
        65, 132,  73, 140, 161,  58, 114, 144, 148, 140, 123, 108,  43,
       103, 151, 140, 175, 124,  91,  71, 143, 139, 143, 121,  60,  59,
       136, 162,  78, 171,  64, 106, 101, 111,  98, 125, 141, 11

In [119]:
data1 = np.arange(10)
data1[:6]

array([0, 1, 2, 3, 4, 5])

In [121]:
data1[::3]

array([0, 3, 6, 9])

In [125]:
orn1 = np.array([10,20,30,40,50])
orn1[1:4]

array([20, 30, 40])

In [129]:
orn1[:3]

array([10, 20, 30])

In [135]:
orn1[::2]

array([10, 30, 50])

In [137]:
orn2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
orn2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
orn2[1]

array([4, 5, 6])

In [155]:
secilen_veriler = orn2[1:,1:]
print(secilen_veriler)

[[5 6]
 [8 9]]


In [183]:
secilen_veriler1 = orn2[:2,:2]
print(secilen_veriler1)

[[1 2]
 [4 5]]


In [189]:
secilen_veriler2 = orn2[:,1]
print(secilen_veriler2)

[2 5 8]


In [193]:
secilen_veriler3 = orn2[1,:]
print(secilen_veriler3)

[4 5 6]
