In [146]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [147]:
#ColumnTransformer(transformers[("encoder",OneHotEncoder([0]))],remainder = "passtrough")

In [148]:
data = pd.read_csv('Data.csv')

cs = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[0])],remainder = "passthrough")

transfer_data = cs.fit_transform(data)
transfer_data

array([[0.0, 1.0, 0.0, 40.0, 72000.0, 'No'],
       [0.0, 0.0, 1.0, 27.0, 48000.0, 'Yes'],
       [1.0, 0.0, 0.0, 30.0, 54000.0, 'No'],
       [0.0, 0.0, 1.0, 38.0, 61000.0, 'No'],
       [0.0, 1.0, 0.0, 40.0, nan, 'Yes'],
       [0.0, 1.0, 0.0, 35.0, 58000.0, 'Yes'],
       [1.0, 0.0, 0.0, nan, 52000.0, 'No'],
       [0.0, 0.0, 1.0, 48.0, 79000.0, 'Yes'],
       [0.0, 1.0, 0.0, 50.0, 83000.0, 'No'],
       [1.0, 0.0, 0.0, 37.0, 67000.0, 'Yes']], dtype=object)

In [149]:
data = {
    
    'Renk' : ['Kırmızı','Yeşil','Mavi','Kırmızı','Yeşil'],
    'Yaş' : [25,32,47,51,62],
    'Maaş' : [50000,60000,120000,80000,90000]
}


df = pd.DataFrame(data)
cs = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[0])],remainder = "passthrough")

transfer_data = cs.fit_transform(df)

df = pd.DataFrame(transfer_data)
df

0    1    2     3         4
0  1.0  0.0  0.0  25.0   50000.0
1  0.0  0.0  1.0  32.0   60000.0
2  0.0  1.0  0.0  47.0  120000.0
3  1.0  0.0  0.0  51.0   80000.0
4  0.0  0.0  1.0  62.0   90000.0

In [150]:
data = pd.read_csv('Data.csv')

cs = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[-1])],remainder = "passthrough")

transfer_data = cs.fit_transform(data)
df = pd.DataFrame(transfer_data)
df

0    1       2     3        4
0  1.0  0.0  Turkey  40.0  72000.0
1  0.0  1.0     USA  27.0  48000.0
2  1.0  0.0   Japan  30.0  54000.0
3  1.0  0.0     USA  38.0  61000.0
4  0.0  1.0  Turkey  40.0      NaN
5  0.0  1.0  Turkey  35.0  58000.0
6  1.0  0.0   Japan   NaN  52000.0
7  0.0  1.0     USA  48.0  79000.0
8  1.0  0.0  Turkey  50.0  83000.0
9  0.0  1.0   Japan  37.0  67000.0

In [151]:
le = LabelEncoder()
data = {
    'Renk' : ['Kırmızı','Yeşil','Mavi','Kırmızı','Yeşil']
}

df = pd.DataFrame(data)

new_data = le.fit_transform(df['Renk'])
new_data


array([0, 2, 1, 0, 2])

In [152]:
df = pd.DataFrame(new_data)
df

0
0  0
1  2
2  1
3  0
4  2

In [153]:
data = pd.read_csv('Data.csv')
df = pd.DataFrame(data)

new_data = le.fit_transform(df['Purchased'])
new_data

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [154]:
y = df.iloc[:,-1]

y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [155]:
df = pd.DataFrame(y)
df

0
0  0
1  1
2  0
3  0
4  1
5  1
6  0
7  1
8  0
9  1

In [156]:
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
y = np.array([0,1,0,1,0])
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)
print(x_train,"train")
print(x_test,"test")

[[ 3  4]
 [ 1  2]
 [ 9 10]
 [ 7  8]] train
[[5 6]] test


In [157]:
print(y_train,"train")
print(y_test,"test")

[1 0 0 1] train
[0] test


In [165]:
ss  = StandardScaler()
print(x_train)
print("*************************************")
x_train[:,3:] = ss.fit_transform(x_train[:,3:])
print(x_train)

[[ 3  4]
 [ 1  2]
 [ 9 10]
 [ 7  8]]
*************************************


ValueError: Found array with 0 feature(s) (shape=(4, 0)) while a minimum of 1 is required by StandardScaler.

In [158]:
data = pd.read_csv('Data.csv')
x = data[]
y = data[]
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)


SyntaxError: invalid syntax (1458452220.py, line 2)